blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.blogList, name='bloglist'),
    path('create/', views.CreateBlog.as_view(), name='create'),
    path('update/<int:pk>/', views.UpdateBlog.as_view(), name='blogupdate'),
    path('article/<int:pk>/', views.articleView, name='viewarticle'),
    path('add-article', views.addArticle, name='add-article'),
    path('edit-article/<int:pk>/', views.modifyArticle, name='edit-article'),
    path('delete-article/<int:pk>/', views.deleteArticle, name='delete-article'),

]

fabio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import *

app_name = 'portfolio'

urlpatterns = [
    path('update/<int:pk>', views.SiteUpdate.as_view(), name='siteupdate'),
    path('delete/<int:pk>', views.SiteDelete.as_view(), name='sitedelete'),
    path('create/', views.siteCreate, name='sitecreate'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.core.validators import MinValueValidator, MaxValueValidator
# Create your models here.


class Post(models.Model):

    name = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=256)
    location = models.CharField(max_length=256, null=True, blank=True)
    propic = models.ImageField(null=True, blank=True)
    text = RichTextUploadingField(blank=True, null=True)
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class Skills(models.Model):

    skill = models.CharField(max_length=256)
    description = RichTextUploadingField(blank=True, null=True)
    created_date = models.DateTimeField(default=timezone.now)
    level = models.IntegerField(validators=[MaxValueValidator(100)])

    def __str__(self):
        return self.skill


class Articles(models.Model):

    author = models.ForeignKey(
        'auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=256)
    description = models.CharField(max_length=150, blank=True, null=True)
    image = models.ImageField(null=True, blank=True,
                              default='default-placeholder.png')
    body = RichTextUploadingField(blank=True)
    visible = models.BooleanField(default=True)
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class Comments(models.Model):
    article = models.ForeignKey(
        'blog.Articles', on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    comment = models.TextField()
    allowed = models.BooleanField(default=True)
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.comment

blog/forms.py
from .models import Post, Skills, Articles, Comments
from django.forms import ModelForm
from django import forms
from django.core.mail import send_mail


class PostForm(ModelForm):

    class Meta:
        model = Post
        fields = ['propic', 'text', 'location']


class ContactForm(forms.Form):

    name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    text = forms.CharField(widget=forms.Textarea())


class SkillForm(ModelForm):

    class Meta:
        model = Skills
        fields = '__all__'


class AddArticleForm(ModelForm):

    class Meta:
        model = Articles
        fields = ['title', 'image', 'body', 'visible']


class CommentForm(ModelForm):

    class Meta:
        model = Comments
        fields = ['name', 'comment']

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, CreateView, DetailView, UpdateView, TemplateView, FormView
from django.core.mail import send_mail
from django.conf import settings
from .models import Post, Skills, Articles, Comments
from portfolio.models import Items
from . import forms
from .forms import PostForm, ContactForm, AddArticleForm, CommentForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.http import Http404
from django.http import HttpResponseRedirect


# Create your views here.

def blogList(request):
    posts = Post.objects.all()
    topSkills = Skills.objects.all().exclude(description="").order_by('-level')
    otherSkills = Skills.objects.all().filter(description="")
    articles = Articles.objects.all().filter(
        visible=True).order_by('created_date')
    project = Items.objects.all()
    form = forms.ContactForm()

    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['text']
            send_mail(
                'Contact Form',
                name + "\n" + email + "\n" + message,
                'settings.EMAIL_HOST_USER',
                ['fabivs9@gmail.com'],
                fail_silently=False,
            )
            messages.success(
                request, f"Thank you for getting in touch, {name}.")
            return redirect('blog:bloglist')
    context = {'posts': posts, 'topSkills': topSkills, 'otherSkills': otherSkills,
               'articles': articles, 'form': form, 'project': project}
    return render(request, 'blog/post_list.html', context)


def articleView(request, pk):
    articles = Articles.objects.get(id=pk)
    article = get_object_or_404(Articles, id=pk)
    comment = Comments.objects.all()
    comment_count = Comments.objects.count()
    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = article
            comment.save()
            return redirect('blog:viewarticle', pk)

    context = {'articles': articles,
               'form': form, 'comment': comment, 'comment_count': comment_count}
    return render(request, 'blog/article.html', context)


def addArticle(request):
    if not request.user.is_authenticated:
        raise Http404
    form = AddArticleForm()

    if request.method == 'POST':
        form = AddArticleForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            if instance.body.startswith("<p>"):
                instance.description = instance.body[3:150]
            elif instance.body.startswith("<"):
                instance.description = instance.body[4:150]
            else:
                instance.description = instance.body[0:150]
            instance.save()
            return redirect('blog:bloglist')
    context = {'form': form}
    return render(request, 'blog/add-article.html', context)


def modifyArticle(request, pk):
    article = Articles.objects.get(id=pk)
    if request.user != article.author:
        raise Http404

    form = AddArticleForm(instance=article)
    if request.method == 'POST':
        form = AddArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            instance = form.save(commit=False)
            if instance.body.startswith("<p>"):
                instance.description = instance.body[3:150]
            elif instance.body.startswith("<"):
                instance.description = instance.body[4:150]
            else:
                instance.description = instance.body[0:150]
            instance.save()
        messages.success(request, 'Updated!')
    context = {'form': form}
    return render(request, 'blog/edit-article.html', context)


def deleteArticle(request, pk):
    article = Articles.objects.get(id=pk)
    if request.user != article.author:
        raise Http404

    if request.method == 'POST':
        article.delete()
        return redirect("blog:bloglist")
    context = {'article': article}
    return render(request, 'blog/delete-article.html', context)


class MustBeAuthorGetObjectMixin:
    def get_object(self):
        obj = super().get_object()
        if obj.name != self.request.user:
            raise PermissionDenied("...")
        return obj


class CreateBlog(LoginRequiredMixin, CreateView):

    model = Post
    form_class = PostForm
    success_url = reverse_lazy('blog:bloglist')


class UpdateBlog(LoginRequiredMixin, MustBeAuthorGetObjectMixin, UpdateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('blog:bloglist')


# class DeleteBlog(LoginRequiredMixin, MustBeAuthorGetObjectMixin, DeleteView):
#     model = Post
#     success_url = reverse_lazy('blog:bloglist')
#
#
# class BlogDetail(DetailView):
#     model = Post

blog/templates/blog/add-article.html
{% extends 'blog/blog_base.html' %}
{% block content %}
{% load bootstrap %}

<div class="container d-flex justify-content-center mt-2 mb-2">
  <form class="" method="post" enctype="multipart/form-data">
    {{ form|bootstrap }}
    {{form.media}}
    {% csrf_token %}
    <input type="submit" name="" value="Submit">
  </form>
</div>
{% endblock %}

blog/templates/blog/article.html
{% extends 'blog/blog_base.html' %}
{% load bootstrap %}
{% block content %}
<div class="container text-center mt-5 text-break">

  <h3>{{articles.title}}</h3>
  {% if not articles.likes %}
  <small>Published on {{articles.created_date}} by {{articles.author}}</small>
  {% else %}
  <small>Published on {{articles.created_date}} by {{articles.author}} - {{articles.likes}} like{{articles.likes|pluralize:"s"}}</small>
  {% endif %}
  <br>
  <img class="article--image  mt-5 mb-5" src="{{articles.image.url}}" alt="">
  <br>
  {{articles.body|safe}}
  {% if user.id == articles.author.id %}
  <div class="">
    <a class="btn btn-warning" href="{% url 'blog:edit-article' articles.pk %}">Edit</a>
    <a class="btn btn-danger" href="{% url 'blog:delete-article' articles.pk %}">Delete</a>
  </div>

  {% endif %}
</div>

<!-- LIKE BUTTON -->
<!-- <form class="" method="post">

  {% for like in form %}
  {% csrf_token %}
  <i onclick="likeButton(this)" class="bi bi-hand-thumbs-up"></i>
  {% endfor %} -->
<!-- <input type="submit" name="" value="submit">
</form> -->
<div class="container article--section--two">
  <hr>
  <h1>Comments</h1>
  <form class="" method="post">
    {% csrf_token %}
    {{form.media}}
    {{form|bootstrap}}
    <input type="submit" name="" value="Submit">
  </form>
  {% for comment in articles.comments_set.all %}
  <div class="container">
    <hr>
    <p class="">From <strong>{{comment.name}}</strong> posted on <small>{{comment.created_date}}</small></p>
    <p>Comment: {{comment.comment|safe}}</p>
  </div>
  {% endfor %}
</div>
{% endblock %}

blog/templates/blog/blog_base.html
<!DOCTYPE html>
{% load static %} {% load bootstrap %}

<html lang="en" dir="ltr">
	<head>
		<script
			async
			src="https://www.googletagmanager.com/gtag/js?id=G-8GKNGN9FZP"
		></script>
		<script>
			window.dataLayer = window.dataLayer || [];
			function gtag() {
				dataLayer.push(arguments);
			}
			gtag('js', new Date());

			gtag('config', 'G-8GKNGN9FZP');
		</script>
		<!-- End Google Tag Manager -->
		<meta charset="utf-8" />
		<title>Fabio Catino - Developer</title>
	</head>
	<link rel="stylesheet" href="{% static '/css/bootstrap.css' %}" />
	<link rel="stylesheet" href="{% static '/css/custom.css' %}" />
	<link
		rel="stylesheet"
		href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
	/>
	<link rel="preconnect" href="https://fonts.gstatic.com" />
	<link
		href="https://fonts.googleapis.com/css2?family=Roboto&display=swap"
		rel="stylesheet"
	/>
	<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />

	{% include 'blog/navbar.html' %}

	<body>
		{% block content %} {% endblock %}
		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
			integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
			crossorigin="anonymous"
		></script>
		<script src="{% static 'js/main.js' %}"></script>
		<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
		<script>
			AOS.init();
		</script>
	</body>
</html>

blog/templates/blog/delete-article.html
{% extends 'blog/blog_base.html' %}
{% load bootstrap %}
{% block content %}

<div class="content d-flex justify-content-center">
  <form class="" method="post">
    <h3 class="mt-5">Are you sure you want to delete it?</h3>
    {% csrf_token %}
    <input class="btn btn-warning" type="submit" name="" value="Yes">
    <a class="btn btn-primary" href="{% url 'blog:viewarticle' article.pk %}">No</a>
  </form>
</div>

{% endblock %}

blog/templates/blog/edit-article.html
{% extends 'blog/blog_base.html' %}
{% load bootstrap %}
{% block content %}

<div class="container">
  <div class="d-flex justify-content-lg-center mt-3">
    <form class="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{form.media}}
      {{ form|bootstrap }}
      {% for message in messages %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endfor %}
      <input type="submit" name="" value="Submit">

    </form>
  </div>

</div>

{% endblock %}

blog/templates/blog/navbar.html
<!-- {% load static %} -->
<nav class="navbar navbar-expand-lg  navbar--theme fabio--navbar  stroke" style="font-size: 20px; ">
  <ul class=" socials list-inline mb-0" style="display: inline-flex !important; align-items: center;">
    <a href="https://www.linkedin.com/in/fabio-catino" target="_blank"><i class="bi bi-linkedin text-white"></i></a>
    <a href="https://github.com/fabiocatino" target="_blank"><i class="bi bi-github text-white"></i></a>
    <a href="https://www.facebook.com/r.riven/" target="_blank"><i class="bi bi-facebook text-white"></i></a>
    <a href="mailto:fabivs9@gmail.com" target="_blank"><i class="bi bi-envelope text-white"></i></a>
  </ul>
  <button class=" navbar-light  navbar-toggler ml-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse navbar--text" id="navbarNav">
    <ul class="navbar-nav ms-auto" style="display: inline-flex !important; align-items: center; font-size: 15px;">
      <li class="nav-item">
        <a class="nav-link active navbar--center" aria-current="page" href="{% url 'blog:bloglist' %}">ABOUT ME</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link active" href="/#portfolio">PORTFOLIO</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" href="/#contact">CONTACT ME</a>
      </li>
      {% if user.is_staff %}
      <li class=" nav-item">
        <a class="nav-link active" href="{% url 'admin:logout' %}">LOG OUT</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

blog/templates/blog/post_form.html
{% extends 'blog/blog_base.html' %}
{% block content %}
<div class="introduction d-flex justify-content-center  ">
  <form method="POST" class="post-form" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    {{form.media}}
    <input type="submit" name="" value="Submit">
  </form>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/blog_base.html' %} {% block content %} {% load static %} 
{%load bootstrap %}

<section class="main--section">
	{% for message in messages %}
	<div
		class="
			alert alert-success alert-dismissible
			fade
			show
			d-flex
			align-self-start
		"
		role="alert"
	>
		{{message}}
		<button
			type="button"
			class="btn-close"
			data-bs-dismiss="alert"
			aria-label="Close"
		></button>
	</div>
	{% endfor %}
	<div class="first--section d-flex justify-content-center">
		<div
			class="media flex-column flex-md-row intro--section col col-md-7 col-sm-4"
		>
			{% for post in posts %}
			<div class="text-center">
				{% if post.propic %}
				<img
					class="img-thumbnail rounded-circle mb-2"
					style="
						height: 250px;
						width: 250px;
						max-width: 250px;
						flex-shrink: 0;
						image-rendering: -webkit-optimize-contrast;
					"
					src=" {{post.propic.url}}"
				/>
				<i class="bi bi-geo-alt">{{ post.location}}</i>

				{% endif %}
			</div>
			<div class="me-auto media-body text-center text-md-start post--text">
				<p class="">{{ post.text|safe }}</p>
				{% if user.id == post.name.id %}
				<a
					class="btn btn-info ciao"
					href=" {% url 'blog:blogupdate' pk=post.pk %}"
					role="button"
					>Modify</a
				>
				{% endif %}
			</div>
		</div>
	</div>
	{% endfor %}
</section>

<section class="skills--section p-5">
	<div class="detail-content container">
		<h1 class="text-center p-2">My Skills</h1>
		<ul class="tool-list">
			{% for skill in topSkills|slice:"0:4" %}
			<div class="specific--skill p-3">
				<li>
					<svg width="200" height="200" viewbox="0 0 100 100">
						<circle cx="50" cy="50" r="45"></circle>
						<circle
							class="cbar"
							cx="50"
							cy="50"
							r="45"
							style="--percent: 0.{{skill.level}}"
						></circle>
					</svg>
					<span class="tl-name"><strong>{{skill.skill|upper}}</strong></span>
					<span class="tl-exp"></span>
					<!-- {{skill.level}}% -->
				</li>
				{{skill.description|safe}}
			</div>
			{% endfor %}
		</ul>
	</div>
	<h3 class="text-center p-2">Other Skills</h3>
	<div class="other--skills--container">
		<div class="other--skills">
			{% for skill in otherSkills %}
			<span
				class="badge rounded-pill skill--badge me-2"
				style="font-size: 20px"
			>
				{{skill}}
			</span>
			{% endfor %}
		</div>
	</div>
</section>

<section
	id="portfolio"
	class="wrapper project--section p-5"
	style="scroll-behavior: auto; background-color: #f7f8fa"
>
	<div class="project-cards-content">
		<div class="container">
			<h1 class="text-center mb-5">My Projects</h1>
			<div class="row d-flex justify-content-center project-cards-content">
				{% for item in project %}
				<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-4 p-2 d-flex justify-content-center">
					<div class="p-card">
						<a
							target="_blank"
							rel="noreferrer"
							class="p-img-card"
							href="{{item.url}}"
							><img src="{{item.image.url}}"
						/></a>
						<div class="p-card-content">
							<h4 class="p-card-title">
								<a target="_blank" rel="noreferrer" href="{{item.url}}"
									>{{item.name|safe}}
								</a>
							</h4>
							{% if item.description %}
							<span class="project--body">{{item.description|safe}}</span>
							{% endif %}
						</div>
						<div class="p-card-tags">
							{% for tag in item.tags.all %}
							<span
								class="badge rounded-pill text-dark"
								style="background-color: #aaacad"
								>{{tag}}</span
							>
							{% endfor %}
						</div>
						<div class="p-card-read-more">
							<a
								target="_blank"
								rel="noopener noreferrer"
								href="{{item.url}}"
								class="btn btn-link btn-block"
							>
								See more
							</a>
							{% if request.user.id == item.author.id %}
							<a href="{% url 'portfolio:siteupdate' item.pk %}"
								><i class="bi bi-pencil"></i>
							</a>
							<a href="{% url 'portfolio:sitedelete' item.pk %}"
								><i class="bi bi-trash"></i>
							</a>
							{% endif %}
						</div>
					</div>
				</div>
				{% endfor %}
			</div>
			{% if request.user.is_authenticated %}
			<a
				class="d-flex justify-content-center mt-5"
				href="{% url 'portfolio:sitecreate' %}"
				><button class="btn btn-primary" type="button" name="button">
					New Post
				</button></a
			>
			{% endif %}
		</div>
	</div>
</section>

<section
	class="wrapper posts--section position-relative p-2"
	style="scroll-behavior: auto"
>
	<div class="content">
		<div class="container">
			<h1 class="text-center p-2">My Posts</h1>
			<div class="row d-flex justify-content-center">
				{% for article in articles %}
				<div
					class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-4 p-3"
					data-aos="slide-right"
					data-aos-anchor-placement="center-bottom"
				>
					<div class="p-card">
						<a class="p-img-card" href="{% url 'blog:viewarticle' article.pk %}"
							><img src="{{article.image.url}}"
						/></a>
						<div class="p-card-content">
							<h4 class="p-card-title">
								<a href="{% url 'blog:viewarticle' article.pk %}"
									>{{article.title|safe}}</a
								>
							</h4>
							<div class="article--info">
								<small class="article--info--link"
									>Posted on {{article.created_date|date:"F jS Y"}}<a
										href="{% url 'blog:viewarticle' article.pk %}"
										><i class="bi bi-chat"></i>
										{{article.comments_set.all.count}}
										Comment{{article.comments_set.all.count|pluralize:"s"}}</a
									></small
								>
								<br />
							</div>
							<div class="article--info">
								<span class="article--body"
									>{{article.description|safe|slice:"0:150"}}...</span
								>
							</div>
						</div>

						<div class="p-card-read-more">
							<a
								href="{% url 'blog:viewarticle' article.pk %}"
								class="btn btn-link btn-block"
							>
								Read More...
							</a>
							{% if request.user.id == article.author.id %}
							<a href="{% url 'blog:edit-article' article.pk %}"
								><i class="bi bi-pencil"></i>
							</a>
							<a href="{% url 'blog:delete-article' article.pk %}"
								><i class="bi bi-trash"></i>
							</a>
							{% endif %}
						</div>
					</div>
				</div>
				{% endfor %} {% if request.user.is_authenticated %}
				<a
					class="d-flex justify-content-center"
					href="{% url 'blog:add-article' %}"
					><button class="btn btn-primary" type="button" name="button">
						New Post
					</button></a
				>
				{% endif %}
			</div>
		</div>
	</div>
</section>

<section
	id="contact"
	style="scroll-behavior: auto; background-color: #41a4f5"
	class="p-5"
>
	<div class="container d-flex justify-content-center">
		<form class="contact--form" method="post">
			<strong>
				<h2 class="d-flex justify-content-center">Get in touch</h2>
			</strong>
			{% for field in form %} {% csrf_token %}
			<label for="">{{field.label}}</label>
			{{field}} {% endfor %}
			<br />
			<input type="submit" class="btn btn-primary" value="Submit" />
		</form>
	</div>
</section>

{% endblock %}